import catalog from "@/lib/exercise-catalog.json";
import { fitnessEquipmentLabels, type FitnessEquipment } from "@/lib/fitness-setup";
import type { MuscleGroup } from "@/lib/exercises";

/**
 * The catalogue: every exercise there is, with instructions.
 *
 * `exercises.ts` is the library the programme is *generated* from — 58 lifts,
 * curated, each carrying the movement pattern the generator sorts by. It stays
 * exactly that size on purpose. This is the other half of the problem: what a
 * lift actually is, how it is performed, and what else trains the same muscle
 * when the gym is busy or the shoulder is complaining.
 *
 * Data and instruction text come from hasaneyldrm/exercises-dataset under the
 * MIT licence, regenerated by `scripts/build-exercise-catalog.mjs`. The images
 * and animations are © Gym visual and are not in this repository; Orbit renders
 * them only when a deployment sets `NEXT_PUBLIC_EXERCISE_MEDIA_BASE`, having
 * settled its own terms with Gym visual first.
 *
 * The JSON is 900 kB, which is a lot to hand a phone and nothing at all to a
 * server. So every function here is called from a server component or a server
 * action, and what reaches the browser is the twenty rows someone searched for.
 */

export type CatalogExercise = {
  /** The upstream body part: "waist", "upper legs", "cardio", … */
  bodyPart: string;
  /** The upstream equipment name: "barbell", "leverage machine", … */
  equipment: string;
  /** Media file names. Meaningless without a configured media base. */
  gif: string;
  /** `cat-0001`. Stable for ever: a logged set may refer to it. */
  id: string;
  image: string;
  name: string;
  secondaryMuscles: string[];
  /** English, one sentence per step. Empty for a handful of entries. */
  steps: string[];
  /** The upstream primary target: "pectorals", "lats", … */
  target: string;
};

type CatalogFile = {
  attribution: string;
  exercises: CatalogExercise[];
  license: string;
  source: string;
};

const file = catalog as CatalogFile;

export const CATALOG: CatalogExercise[] = file.exercises;

/** Shown wherever a picture from the dataset is shown. Not optional. */
export const CATALOG_ATTRIBUTION = file.attribution;
export const CATALOG_SOURCE = file.source;

/**
 * Upstream targets to the ten groups Orbit counts a week against.
 *
 * The mapping is lossy on purpose and in the same direction `exercises.ts`
 * already chose: forearms, traps and the rest are folded into the movement
 * that trains them, because a list you cannot honestly count to two on makes
 * the twice-a-week rule meaningless. Cardio has no muscle group at all, and
 * saying so is more honest than filing a treadmill under quads.
 */
const TARGET_TO_MUSCLE: Record<string, MuscleGroup | null> = {
  abdominals: "core",
  abductors: "glutes",
  abs: "core",
  adductors: "quads",
  biceps: "biceps",
  calves: "calves",
  "cardiovascular system": null,
  delts: "shoulders",
  forearms: "biceps",
  glutes: "glutes",
  hamstrings: "hamstrings",
  lats: "back",
  "levator scapulae": "shoulders",
  pectorals: "chest",
  quads: "quads",
  "serratus anterior": "chest",
  spine: "back",
  traps: "back",
  triceps: "triceps",
  "upper back": "back",
};

/** The muscle group Orbit counts this exercise under, or null for cardio. */
export function catalogMuscle(exercise: CatalogExercise): MuscleGroup | null {
  return TARGET_TO_MUSCLE[exercise.target.toLowerCase()] ?? null;
}

/**
 * Upstream equipment to the five kits Orbit's setup asks about.
 *
 * Anything that is a specific piece of gym furniture is `full_gym`, because
 * that is the honest answer to "can I do this today": a sled, a hack squat and
 * a leverage machine are all things you either have a gym for or you do not.
 * Only the four kits someone can genuinely own at home get their own answer.
 */
const EQUIPMENT_TO_KIT: Record<string, FitnessEquipment[]> = {
  assisted: ["full_gym"],
  band: ["bands"],
  barbell: ["full_gym"],
  "body weight": ["bodyweight"],
  "bosu ball": ["full_gym"],
  cable: ["full_gym"],
  dumbbell: ["dumbbells"],
  "elliptical machine": ["cardio"],
  "ez barbell": ["full_gym"],
  hammer: ["full_gym"],
  kettlebell: ["full_gym"],
  "leverage machine": ["full_gym"],
  "medicine ball": ["full_gym"],
  "olympic barbell": ["full_gym"],
  "resistance band": ["bands"],
  roller: ["full_gym"],
  rope: ["full_gym"],
  "skierg machine": ["cardio"],
  "sled machine": ["full_gym"],
  "smith machine": ["full_gym"],
  "stability ball": ["full_gym"],
  "stationary bike": ["cardio"],
  "stepmill machine": ["cardio"],
  tire: ["full_gym"],
  "trap bar": ["full_gym"],
  "upper body ergometer": ["cardio"],
  weighted: ["full_gym"],
  "wheel roller": ["full_gym"],
};

/** The kits any one of which is enough to do it. Unknown gear needs a gym. */
export function catalogKit(exercise: CatalogExercise): FitnessEquipment[] {
  return EQUIPMENT_TO_KIT[exercise.equipment.toLowerCase()] ?? ["full_gym"];
}

const byId = new Map(CATALOG.map((exercise) => [exercise.id, exercise]));

export function getCatalogExercise(id: string): CatalogExercise | null {
  return byId.get(id) ?? null;
}

/** True for an id this module owns, so a caller can route a lookup. */
export function isCatalogId(id: string) {
  return id.startsWith("cat-");
}

/**
 * The curated lift, and the catalogue entry that explains it.
 *
 * Hand-written, and short on purpose. Nine of Orbit's lifts have no honest
 * equivalent upstream — there is no face pull in the dataset, and no plank
 * that is not a plank with a twist in it — and a near-enough match would put
 * the wrong instructions under the right name, which is worse than none. Those
 * simply have no entry here, and the screen says nothing rather than something
 * untrue.
 */
const CURATED_TO_CATALOG: Record<string, string> = {
  "ab-wheel": "cat-0857",
  "back-squat": "cat-0043",
  "band-curl": "cat-0968",
  "barbell-bench-press": "cat-0025",
  "barbell-curl": "cat-0031",
  "barbell-row": "cat-0027",
  "bulgarian-split-squat": "cat-0410",
  "cable-crunch": "cat-0175",
  "cable-curl": "cat-0868",
  "cable-fly": "cat-0188",
  "cable-kickback": "cat-0228",
  "chin-up": "cat-1326",
  "close-grip-bench-press": "cat-0030",
  deadlift: "cat-0032",
  "decline-push-up": "cat-0279",
  "diamond-push-up": "cat-0283",
  dips: "cat-0814",
  "dumbbell-bench-press": "cat-0289",
  "dumbbell-curl": "cat-0294",
  "dumbbell-row": "cat-0292",
  "dumbbell-shoulder-press": "cat-0405",
  "farmer-carry": "cat-2133",
  "front-squat": "cat-0042",
  "glute-bridge": "cat-3013",
  "goblet-squat": "cat-1760",
  "hammer-curl": "cat-0313",
  "hanging-leg-raise": "cat-0472",
  "hip-thrust": "cat-3562",
  "incline-dumbbell-press": "cat-0314",
  "inverted-row": "cat-0499",
  "lat-pulldown": "cat-0150",
  "lateral-raise": "cat-0334",
  "leg-extension": "cat-0585",
  "leg-press": "cat-0739",
  "lying-leg-curl": "cat-0586",
  "machine-chest-press": "cat-0577",
  "nordic-curl": "cat-0496",
  "overhead-press": "cat-0091",
  "overhead-triceps-extension": "cat-0194",
  "pull-up": "cat-0652",
  "push-up": "cat-0662",
  "rear-delt-fly": "cat-2292",
  "romanian-deadlift": "cat-0085",
  "seated-cable-row": "cat-0861",
  "seated-calf-raise": "cat-0594",
  "single-leg-calf-raise": "cat-0409",
  "single-leg-glute-bridge": "cat-3645",
  "single-leg-romanian-deadlift": "cat-1757",
  "standing-calf-raise": "cat-1373",
  "triceps-pushdown": "cat-0241",
  "walking-lunge": "cat-1460",
};

/**
 * The catalogue entry behind any exercise id Orbit can log, curated or not, or
 * null when there is nothing honest to show.
 */
export function catalogEntryFor(exerciseId: string): CatalogExercise | null {
  if (isCatalogId(exerciseId)) return getCatalogExercise(exerciseId);
  const linked = CURATED_TO_CATALOG[exerciseId];
  return linked ? getCatalogExercise(linked) : null;
}

/** Every body part present, most exercises first — the filter row's order. */
export const CATALOG_BODY_PARTS: string[] = [
  ...new Map(
    CATALOG.map((exercise) => [exercise.bodyPart, exercise.bodyPart]),
  ).keys(),
].sort((a, b) => count(b) - count(a) || (a < b ? -1 : 1));

function count(bodyPart: string) {
  return CATALOG.filter((exercise) => exercise.bodyPart === bodyPart).length;
}

/**
 * The equipment worth offering for a list that is already filtered, most
 * common first. Deriving it from the filtered list rather than from the whole
 * catalogue keeps the row short and means every chip on screen has results
 * behind it.
 */
export function equipmentInList(list: CatalogExercise[]): string[] {
  const counts = new Map<string, number>();
  for (const exercise of list) {
    if (!exercise.equipment) continue;
    counts.set(exercise.equipment, (counts.get(exercise.equipment) ?? 0) + 1);
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1))
    .map(([equipment]) => equipment);
}

/** Accents off, case off — the search box is typed into on a phone. */
function normalize(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
}

export type CatalogQuery = {
  bodyPart?: string;
  equipment?: string;
  /** Only what this kit can do. Undefined means show everything. */
  kit?: FitnessEquipment[];
  muscle?: MuscleGroup;
  search?: string;
};

/**
 * The catalogue, filtered.
 *
 * Every word typed has to match somewhere in the name, so "cable row" narrows
 * rather than widens — the opposite behaviour turns 1 324 exercises into a
 * list that always has everything in it. A name that starts with the search
 * sorts first, because "row" should reach "row" before "barbell bent-over row".
 */
export function searchCatalog(query: CatalogQuery): CatalogExercise[] {
  const terms = normalize(query.search ?? "")
    .split(/\s+/)
    .filter(Boolean);
  const kit = query.kit ? new Set(query.kit) : null;

  const matched = CATALOG.filter((exercise) => {
    if (query.bodyPart && exercise.bodyPart !== query.bodyPart) return false;
    if (query.equipment && exercise.equipment !== query.equipment) return false;
    if (query.muscle && catalogMuscle(exercise) !== query.muscle) return false;
    if (kit && !catalogKit(exercise).some((item) => kit.has(item))) return false;
    if (terms.length === 0) return true;
    const name = normalize(exercise.name);
    return terms.every((term) => name.includes(term));
  });

  if (terms.length === 0) return matched;

  const first = terms[0];
  return matched.sort((a, b) => {
    const rank =
      Number(normalize(b.name).startsWith(first)) -
      Number(normalize(a.name).startsWith(first));
    return rank || (a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
  });
}

/**
 * Where the pictures live, or nothing.
 *
 * The animations are © Gym visual and this repository does not carry them, so
 * the default is no media at all and the catalogue reads perfectly well without
 * it: a name, the muscle, the kit and the steps. A deployment that has settled
 * its own terms with Gym visual points this at its copy and the pictures appear.
 */
export function catalogMediaBase(): string {
  const base = process.env.NEXT_PUBLIC_EXERCISE_MEDIA_BASE ?? "";
  return base ? base.replace(/\/+$/, "") : "";
}

export function catalogImageSrc(exercise: CatalogExercise): string {
  const base = catalogMediaBase();
  return base && exercise.image ? `${base}/img/${exercise.image}` : "";
}

export function catalogGifSrc(exercise: CatalogExercise): string {
  const base = catalogMediaBase();
  return base && exercise.gif ? `${base}/gif/${exercise.gif}` : "";
}

/**
 * A catalogue entry flattened into the handful of strings a screen shows.
 *
 * The reason this type exists is the client boundary. The session log is a
 * client component, and anything it imports goes to the phone — so it is
 * handed finished sentences instead of the module that could produce them.
 */
export type ExerciseGuide = {
  attribution: string;
  /** Body part, muscle group, equipment, kit — the chips above the steps. */
  facts: string[];
  /** The animation if a deployment has licensed one, else the still, else "". */
  mediaSrc: string;
  name: string;
  secondaryMuscles: string[];
  steps: string[];
};

export function buildExerciseGuide(entry: CatalogExercise): ExerciseGuide {
  const muscle = catalogMuscle(entry);
  return {
    attribution: CATALOG_ATTRIBUTION,
    // Deduplicated: "chest" is both the body part and the muscle group for
    // half the chest exercises, and a row that says chest twice reads as a bug.
    facts: [
      ...new Set(
        [
          entry.bodyPart,
          muscle ?? "cardio",
          entry.equipment,
          catalogKit(entry)
            .map((item) => fitnessEquipmentLabels[item])
            .join(" or "),
        ]
          .filter(Boolean)
          .map((fact) => fact.toLowerCase()),
      ),
    ],
    mediaSrc: catalogGifSrc(entry) || catalogImageSrc(entry),
    name: entry.name,
    secondaryMuscles: entry.secondaryMuscles,
    steps: entry.steps,
  };
}

/** The guide for any exercise id Orbit can log, or null when there is none. */
export function guideFor(exerciseId: string): ExerciseGuide | null {
  const entry = catalogEntryFor(exerciseId);
  return entry ? buildExerciseGuide(entry) : null;
}
